import java.util.HashMap;
public class words{
    HashMap<String,String> hMap;
    public  HashMap<String,String> addToDictionary(){

        hMap = new HashMap<>();
        hMap.put("acute","\nሀይለኛ ፤ አስቸጋሪ");
        hMap.put("almighty","\nሀያሉ");
        hMap.put("apostasy","\nሀይማኖትን መተው");
        hMap.put("asperity","\nሀይለ ቃል");
        hMap.put("assignee","\nሀላፊነት የተሰጠው");
        hMap.put("arsenic","\nሀይለኛ መርዝ");
        hMap.put("abase","\nማፈር ፤ መዋረድ");
        hMap.put("ability","\nችሎታ፤ ተሰጣኦ");
        hMap.put("ache","\nህመም ፤ ዉጋት");
        hMap.put("advisory","\nአማካሪ");
        hMap.put("aback","\nመገረም፣ መደነቅ፤ መደንገጥ፣ መበሳጨት");
        hMap.put("abasement","\nውርደት");
        hMap.put("abbey","\nገዳም");
        hMap.put("abject","\nአሰቃቂ");
        hMap.put("abnormal","\nያልተለመደ፤ ከተፈጥሮ የተለየ");
        hMap.put("abolition","\nማጥፋት፤ መደምሰስ");
        hMap.put("abstract","\nረቂቅ");
        hMap.put("absolutely","\nበፍፁም፤ በጭራሽ");
        hMap.put("absurd","\nዘበት፤ የማይመስል");
        hMap.put("absolute","\nፍፁም፤ የተሟላ");
// Words starts with"B"
        hMap.put("band dog","\nሀይለኛ ውሻ");
        hMap.put("bile","\nሀሞት");
        hMap.put("bogey","\nፍርሃት");
        hMap.put("brain wash","\nሀሳብ አስለወጠ");
        hMap.put("broken hearted","\nሀዘን የተጫነው");
        hMap.put("bull headed","\nሀሳበ ግትር፤ መንቻካ");
        hMap.put("bulldog","\nሀይለኛ ውሻ");
        hMap.put("bum","\nሀላፊነት የሚሰማው፤ ቂጥ");
        hMap.put("beggar","\nለማኝ");
        hMap.put("back","\nጀርባ");
        hMap.put("bag","\nቦርሳ");
        hMap.put("bacteria","\nረቂቃን ነፍሳት፤ ባክቴሪያ");

        hMap.put("bandit","\nሽፍታ");
        hMap.put("bankrupt","\nአከሰረ");
        hMap.put("barren","\nመኻን፤ ባዶ");
        hMap.put("bear","\nድብ፤ ስርአተ ቢስ ሰው");
        hMap.put("beach","\nየባህር ዳርቻ");
        hMap.put("beard","\nጢም");
        hMap.put("behold","\nአየ፤ እነሆ");
//Words Starts with"C"
        hMap.put("calve","\nወልደት (ጥጃ)");
        hMap.put("camp","\nሰፈረ");
        hMap.put("canon","\nህግ ፤ ደንብ");
        hMap.put("canton","\nግዛት");
        hMap.put("certify","\nአረጋገጠ ፤ መሰከረ");
        hMap.put("char","\nአሳረረ");
        hMap.put("chisel","\nመሮ");
        hMap.put("civilly","\nየሰለጠነ ፤ መልካም");
        hMap.put("claw","\nጥፍር");
        hMap.put("conductor","\nመሪ ፤ አስተላላፊ");
// D
        hMap.put("dough","\nሊጥ ፤ ጥሩ ከሰል");
        hMap.put("duke","\nመስፍን");
        hMap.put("demolish","\nማውደም ፤ ማጥፋት");
        hMap.put("denounce","\nነቀፈ፤አወገዘ");
        hMap.put("density","\nእፍጋት");
        hMap.put("despoil","\nበዘበዘ");
        hMap.put("destiny","\nአላማ ፤ እድል");
        hMap.put("dim","\nደብዛዛ");
        hMap.put("dish","\nሳህን(ክብ የሆነ)");
        hMap.put("display","\nአሳየ");
// E
        hMap.put("expose","\nአጋለጠ ፤ ገለጠ");
        hMap.put("expressive","\nበተለየ ፤ ገላጭ");
        hMap.put("each","\nበየ፤ አንዳንድ");
        hMap.put("eager","\nዝግጁ፤ የጓጓ");
        hMap.put("eagerness","\nጉጉት");
        hMap.put("eagle","\nንስር አሞራ");
        hMap.put("earache","\nየጆሮ ህመም");
        hMap.put("early","\nየጥንት፤ ፈጠን ያለ");
        hMap.put("earmark","\nምልክት");
        hMap.put("earn","\nአስገኘለት፤ አገኘ");
        hMap.put("earring","\nጉትቻ");
        hMap.put("ease","\nምቾት");
//F
        hMap.put("fab","\nአስደናቂ");
        hMap.put("fabrication","\nየፈጠራ ወሬ፤ ማምረት");
        hMap.put("facile","\nቀልጣፋ፤ ቀላል");
        hMap.put("fact","\nእውነት፤ ነገር፤ ማስረጃ");
        hMap.put("fade","\nአደበዘዘ");
        hMap.put("federate","\nተቀናጀ፤ ተጣመረ");
        hMap.put("felicity","\nሀሴት፤ ከፍተኛ ደስታ");
        hMap.put("feel for","\nራራ፤ አዘነለት");
        hMap.put("filter","\nማጥለያ");
        hMap.put("fit","\nተገቢ፤ ተስማሚ");
        //g
        hMap.put("gab","\nአፍ");
        hMap.put("gate","\nበር");
        hMap.put("gifted","\nተሰጥኦ ያለው");
        hMap.put("gird on","\nታጠቀ");
        hMap.put("glad","\nየደስታ፤ የሚያስደስት/ አስደሳች");
        hMap.put("glare","\nግልምጫ፤ ነፀብራቅ፤ ብርሀን");
        hMap.put("glunch","\nየኩርፊያ አስተያየት");
        hMap.put("go together","\nተወዳጀ፤ ተስማማ");
        hMap.put("grace","\nምህረት፤ ፀጋ፤ ደግነት፤ ባለሟልነት፤ ውበት");
        hMap.put("grand","\nየተከበረ፤ ታላቅ፤ ግርማ ሞገስ ያለው");
        //H
        hMap.put("habit","\nልማድ");
        hMap.put("hack","\nቆረጠ፤ በአርግጫ መታ");
        hMap.put("hat","\nባርኔጣ");
        hMap.put("heave","\nከፍ ዝቅ አለ፤ ጉብ አለ");
        hMap.put("hero","\nጀግና፤ ዋና ባለታሪክ");
        hMap.put("hesitate","\nአመነታ");
        hMap.put("highland","\nደጋ");
        hMap.put("hire","\nተከራየ፤ ቀጠረ");
        hMap.put("hock","\nቋንጃ");
        hMap.put("hook","\nመስቀያ፤ መንጠቆ");
//I
        hMap.put("ice","\nበረዶ");
        hMap.put("ignoble","\nየሚያሣፍር፤ ወራዳ");
        hMap.put("ignite","\nፈነዳ፤ ነደደ፤ እሳት፤ ተያያዘ");
        hMap.put("ill","\nመቅሰፍት፤ በሽታ፤ ቂም፤ ክፉ");
        hMap.put("ignore","\nችላ አለ");
        hMap.put("impairment","\nአድካሚ፤ ሽፋኝ፤ ጋራጅ");
        hMap.put("inadequate","\nየማይበቃ");
        hMap.put("inevitable","\nየማይቀር፤ የማይጠረጠር");
        hMap.put("injury","\nቁስል፤ ጐዳት፤ ማዋረድ");
        hMap.put("inspire","\nመንፈሱን አነሰሳ፤ ቀሰቀሰ");
//J
        hMap.put("jab","\nተከለ፤ ወጋ፤ ጎሸመ");
        hMap.put("judge","\nአስተዋለ፤ ገመተ፤ ውሳኔ ሰጠ፤ ፈረደ");
        hMap.put("junk","\nትርኪ ምርኪ፤ ውዳቂ ነገር፤ ሰልባጅ");
        hMap.put("jail","\nእስር ቤት፤ እስራት");
        hMap.put("jest","\nአፌዘ");
        hMap.put("jinks","\nመቦረቅ");
        hMap.put("join","\nአስተሳሰረ፤ አገጣጠመ የ.. አባል ሆነ፤ ከ.. ገባ");
        hMap.put("journeyer","\nተጓዥ");
        hMap.put("junior","\nታናሽ፤ የበታች");
        hMap.put("junction","\nመገናኛ");
//words starting with K
        hMap.put("keen" , "\nንቁ፤ ስል፤ ከፍ ያለ");
        hMap.put("keep" , "\nቋጠረ፤ ያዘ፤ አስቀመጠ፤ አስተዳደረ");
        hMap.put("keg" , "\nትንሽ በርሜል");
        hMap.put("kennel" , "\nየውሻ ቤት");
        hMap.put("key" , "\nአገላለጽ፤ ፍንጭ፤ ቁልፍ፤ ዋና በር");
        hMap.put("kick" , "\nለጋ፤ ረገጠ");
        hMap.put("kid" , "\nህፃን፤ ግልገል");
        hMap.put("kill" , "\nአጠፋ፤ ገደለ፤ ውድቅ አደረገ");
        hMap.put("killjoy" , "\nበጥባጭ");
        hMap.put("kin" , "\nዘመድ");
        hMap.put("kind" , "\nመልካም፤ ደግ");
        hMap.put("kindle" , "\nቀላ፤ ነደደ፤ አበራ");
        hMap.put("king" , "\nንጉስ");
        hMap.put("kingdom" , "\nግዛት");
        hMap.put("kite" , "\nወላንዶ፤ ጭልፊት");
        hMap.put("kitten" , "\nየድመት ግልገል");
        hMap.put("knee" , "\nጉልበት");
        hMap.put("knock" , "\nመንኳኳት");
        hMap.put("knoll" , "\nሞላላ ኮረብታ፤ ጉብታ");
        hMap.put("knot" , "\nአይን(የእንጨት)፤ ቋጠሮ፤ የመስመሮች መጋጠሚያ፤ በጋብቻ መተሳሰር");
        hMap.put("knowledge" , "\nችሎታ፤ እውቀት፤ መቻል");
//words starting with L
        hMap.put("label" , "\nምልክት");
        hMap.put("labor" , "\nተንገላታ፤ ብዙ ደከመ፤ ሰራ፤ ጣረ");
        hMap.put("lack" , "\nእጥረት፤ እጦት");
        hMap.put("lady" , "\nሴት ወይዘሮ፤ ባለቤት፤ ወይዘሮ");
        hMap.put("lake" , "\nሀይቅ");
        hMap.put("lamb" , "\nየበግ ጠቦት");
        hMap.put("lane" , "\nጠባብ መንገድ፤ የእግር መንገድ፤ ለሯጮች የሚሰመር መስመር");
        hMap.put("large" , "\nብዙ፤ ሰፊ፤ ግዙፍ");
        hMap.put("leader" , "\nአለቃ፤ መሪ");
        hMap.put("leaf" , "\nቅጠል");
        hMap.put("lean" , "\nተደገፈ፤ ዘመመ");
        hMap.put("legend" , "\nመግለጫ፤ አፈታሪክ፤ ጽሁፍ");
        hMap.put("let" , "\nፈቀደ፤ አከራየ");
        hMap.put("letter" , "\nደብዳቤ፣ ፈደል");
        hMap.put("level" , "\nመጠን፤ ደረጃ፤ ፎቅ");
        hMap.put("liana" , "\nሀረግ");
        hMap.put("liberty" , "\nመብት፤ ነፃነት");
        hMap.put("lid" , "\nክዳን፤ መክደኛ");
        hMap.put("light" , "\nመልክ፤ ክብሪት፤ ብርሀን");
        hMap.put("limit" , "\nልክ");
        hMap.put("listen" , "\nሰማ፤ አዳመጠ");
        hMap.put("live" , "\nኖረ፤ ተዳደረ");
        hMap.put("load" , "\nጭነት፤ ሸክም");
        hMap.put("log" , "\nማስታወሻ ደብተር፤ ግንድ");
//words starting with M
        hMap.put("mac" , "\nልብስ (የዝናብ)");
        hMap.put("mace" , "\nዱላ/ ባለብረት እንደ መሣሪያ የሚያገለግል");
        hMap.put("macro" , "\nበጣም ትልቅ/ ሰፊ ነገር የያዘ እንደማለት");
        hMap.put("magic" , "\nምትሐት አስማት መተት");
        hMap.put("maid" , "\nየቤት ሠራተኛ ሴት");
        hMap.put("major" , "\nዋና ትልቅ የተከበረ");
        hMap.put("manor" , "\nቤት እርሻ መሀል ያለ የባለእርስቱ");
        hMap.put("mead" , "\nጠጅ");
        hMap.put("measure" , "\nመለኪያ መስፈሪያ");
        hMap.put("medic" , "\nሀኪም የሕክምና ተማሪ");
        hMap.put("meet" , "\nተገናኘ አገኘ");
        hMap.put("melancholy" , "\nአሳዛኝ");
        hMap.put("mere" , "\nብቻ በቀላሉ");
        hMap.put("middle" , "\nአማካይ");
        hMap.put("mild" , "\nረጋ ያለ ለሰው");
        hMap.put("mine" , "\nየተቀበረ ፈንጅ");
        hMap.put("minute" , "\nኢምንት");
        hMap.put("mirage" , "\nከሩቅ ውሀ ያለ የሚመስል");
        hMap.put("misfit" , "\nየማይገጥም ከሰው ጋር");
        hMap.put("mist" , "\nጭጋግ");
        hMap.put("mock" , "\nአፌዘ አሾፈ");
        hMap.put("monarchy" , "\nንጉሳዊ አገዛዝ");
        hMap.put("mule" , "\nበቅሎ");
        hMap.put("mutual" , "\nየወል የጋራ የሁለት");
//words starting with N
        hMap.put("name" , "\nስያሜ መጠሪያ");
        hMap.put("nap" , "\nሸለብታ በተለይ ለቀን");
        hMap.put("nape" , "\nማጅራት");
        hMap.put("nark" , "\nተናደደ አናደደ");
        hMap.put("nasty" , "\nአስቀያሚ ቀፋፊ ቆሻሻ");
        hMap.put("native" , "\nተወላጅ የአገሬው ሰው ኗሪው");
        hMap.put("near" , "\nቅርብ");
        hMap.put("neat" , "\nንፁሕ ደረቅ አልኮል መጠጥ");
        hMap.put("necessary" , "\nአስፈላጊ ጠቃሚ");
        hMap.put("nectar" , "\nየአበባ ማር");
        hMap.put("negate" , "\nተቃወመ ሰረዘ");
        hMap.put("neigh" , "\nየፈረስ ድምፅ");
        hMap.put("nest" , "\nየወፍ ጎጆ");
        hMap.put("news" , "\nወሬ ዜና");
        hMap.put("niche" , "\nለባታው ተስማሚ ሰው");
        hMap.put("night" , "\nምሽት ማታ");
        hMap.put("nimble" , "\nፈጣን ቀልጣፋ");
        hMap.put("no" , "\nአይ አይሆንም አይደለም");
        hMap.put("noble" , "\nየተከበረ የሚደነቅ");
        hMap.put("nonchalant" , "\nግድየለሽ");
        hMap.put("north" , "\nሰሜን");
        hMap.put("note" , "\nማስታወሻ ትኩረት");
        hMap.put("nova" , "\nብልጭ ድርግም የሚል ኮከብ");
        hMap.put("null" , "\nዋጋ ቢስ");
        hMap.put("numeral" , "\nአሀዝ");
        hMap.put("numb" , "\nአደነዘዘ ስሜትን");
//words starting with O
        hMap.put("oak" , "\nበሉጥ የዛፍ ዓይነት");
        hMap.put("oasis" , "\nዛፍና ውሀ ያለው የበረሀ ቦታ");
        hMap.put("obey" , "\nታዛዥ ትእዛዝ የተቀበለ");
        hMap.put("oblivion" , "\nመርሳት ሙሉ በሙሉ");
        hMap.put("occasion" , "\nአመቺ ጊዜ");
        hMap.put("ocular" , "\nየአይን");
        hMap.put("odorous" , "\nየሚሸት ሽታ ያለው");
        hMap.put("offend" , "\nአስከፋ");
        hMap.put("oil" , "\nዘይት");
        hMap.put("okay" , "\nተስማማ ፈቀደ");
        hMap.put("old" , "\nየቆየ");
        hMap.put("omen" , "\nገጽ ምልክት");
        hMap.put("onion" , "\nቀይ ሽንኩርት");
        hMap.put("opacity" , "\nብርሀን አለማስተላለፍ መጋረድ");
        hMap.put("open" , "\nክፍት");
        hMap.put("opinion" , "\nግላዊ አመለካከት የግል አስተያየት");
        hMap.put("orbit" , "\nምህዋር");
        hMap.put("ore" , "\nአለት አፈር ብረት የሚወጣበት");
        hMap.put("oscillate" , "\nተወዛወዘ");
        hMap.put("otiose" , "\nየማይፈለግ ቃል ሀሳብ");
        hMap.put("oust" , "\nአስወገደ በሀይል አስወጣ ቦታን ለመውሰድ");
        hMap.put("overcome" , "\nአሸነፈ");
        hMap.put("ox" , "\nበሬ");
//p
        hMap.put("pacifism", "\nፀረ ጦርነት አቋም እምነተ");
        hMap.put("pack","\nሸፈነ,ታጠቀ ተሸከመ");
        hMap.put("paddle","\nማማሰያ");
        hMap.put("page","\nገፅ");
        hMap.put("painful","\nየሚያሳዝን");
        hMap.put("pagan","\nየክርስትና የእስልምናና የአይሁድ እምነቶች ተከታይ ያልሆነ");
        hMap.put("padre","\nቄስ");
        hMap.put("paediatrician","\nየህፃናት ሐኪም");
        hMap.put("porous","\nቀዳዳ ያለው");
        hMap.put("pace","\nተንጎራደደ");
        hMap.put("pace off","\nበእርምጃ ለካ");
        hMap.put("public","\nየህዝብ ሕዝብ");
        hMap.put("pub","\nመጠጥ ቤት");
        hMap.put("podium","\nመድረክ");
        hMap.put("poignant","\nአሳዛኝ");
        hMap.put("point","\nሶኬት መሰኪያ");
        hMap.put("pudding","\nጣፋጭ ምግብ");
        hMap.put("puerile","\nቂላቂል ህፃናት");
        hMap.put("pugilism","\nቡጢ ቦክስ");
        hMap.put("portal","\nመግቢያ ትልቅ በር");
//q
        hMap.put("quack","\nአስካካ እንደ ዳክዬ");
        hMap.put("quaff","\nብዙ መጎንጨት");
        hMap.put("quagmire","\nረግረግ");
        hMap.put("qualified","\nብቁ");
        hMap.put("quantity","\nየብዛት የመጠን");
        hMap.put("quarry","\nየሚታደን እንስሳ");
        hMap.put("quick","\nፈጣን");
        hMap.put("queasy","\nየማቅለሽለሽ ስሜት");
        hMap.put("quient","\nሰላማዊ");
        hMap.put("quoth","\nአለ");
        hMap.put("quark","\nየአተም ክፋይ");
        hMap.put("quash","\nሰረዘ , አገደ");
        hMap.put("quarter","\nከአራት አንድ ሩብ");
        hMap.put("quibble","\nተከራከረ");
        hMap.put("quell","\nአረጋጋ");
        hMap.put("quickly","\nበፍጥነት");
        hMap.put("quit","\nጥሎ ሄደ");
        hMap.put("quits","\nተቻቻለ");
        hMap.put("question","\nጥያቄ");
//r
        hMap.put("reach","\nደረሰ");
        hMap.put("roar","\nማጓራት");
        hMap.put("run","\nመሮጥ");
        hMap.put("racism","\nዘረኝነት");
        hMap.put("rubber band","\nየእጅ ላስቲክ");
        hMap.put("ruffian","\nወሮበላ");
        hMap.put("rugged","\nኩሩ");
        hMap.put("road","\nመንገድ");
        hMap.put("rack","\nየሰው ማሰቃያ");
        hMap.put("radial","\nእንደጨረር የተደረደረ");
        hMap.put("roach","\nትንሽ አሳ");
        hMap.put("roast","\nቆላ");
        hMap.put("robe","\nካባ ለበሰ");
        hMap.put("rocket","\nተወናጨፈ");
        hMap.put("roe","\nትንሽ ድብ");
        hMap.put("roll","\nበዝግታ ማለፍ");
        hMap.put("rubbish","\nበጣም ተቸ");
        hMap.put("rude","\nጥንታዊ ቀላል");
//s
        hMap.put("sabbath","\nሰንበት");
        hMap.put("sabotage","\nበስውር የፈረሰ");
        hMap.put("saccharine","\nበጣምየሚጣፍጥ");
        hMap.put("suave","\nጠፍ ያለ");
        hMap.put("sub","\nተተኪ ተቀያሪ");
        hMap.put("soil","\nአፈር");
        hMap.put("sick","\nበሽተኛ ህመሙ");
        hMap.put("sack","\nጆንያ ከረጢት ሙሉ");
        hMap.put("sea","\nባህር ሞገድ");
        hMap.put("seagoing","\nባህር አቋራጭ");
        hMap.put("seam","\nመጋጠሚያ");
        hMap.put("search","\nፍለጋ");
        hMap.put("season","\nወቅት");
        hMap.put("sacred promise","\nቅዱስ ቃልኪዳን");
        hMap.put("sad","\nሀዘንተኛ");
        hMap.put("saddle","\nጫነ");
        hMap.put("safari","\nየአደን ኮት");
        hMap.put("so as to","\nእንደ");
//t
        hMap.put("table","\nጠረጴዛ");
        hMap.put("tea","\nሻይ ቅጠል");
        hMap.put("toad","\nጉርጥ");
        hMap.put("toast","\nጠበሰ ዳቦ");
        hMap.put("today","\nዛሬ");
        hMap.put("toilet","\nየመፀዳጃ ቤት እቃ");
        hMap.put("tolerance","\nትእግስት");
        hMap.put("toll","\nደወል የሀዘን");
        hMap.put("tomorrow","\nነገ");
        hMap.put("tabernacle","\nየሙሴ ፅላት");
        hMap.put("trace","\nርዝራዥ");
        hMap.put("treachery","\nስብቀት");
        hMap.put("tube","\nቱቦ");
        hMap.put("tug","\nመነጨቀ ጎተተ");
        hMap.put("tuition","\nየመማሪያ ክፍያ");
        hMap.put("tummy","\nሆድ ከርስ");
        hMap.put("teacup","\nየሻይ ስኒ");
        hMap.put("tear","\nቀደደ");
//u
        hMap.put("unborn" , "\nወደ ፊት የሚመጣ");
        hMap.put("unconscious" , "\nሳያስቡት የተደረገ አእምሮውን የሳተ");
        hMap.put("underpass" ,"\nመሿለኪያ");
        hMap.put("undoing", "\nውድቀት");
        hMap.put("unearth" , "\nአገኘ፤ መሬት ቆፍሮ ወጣ");
        hMap.put("uneven" , "\nያልተስተካከለ");
        hMap.put("unfounded" , "\nመሰረት የሌለው");
        hMap.put("unharmonious" , "\nያልተቀናበረ");
        hMap.put("unison" , "\nተባብረው");
        hMap.put("unlawful" , "\nህገወጥ ክልክል");
//v
        hMap.put("visiting" ,"\nእንግዳ");
        hMap.put("vocabulary" ,"\nመዝገበ ቃላት");
        hMap.put("voltmeter" ,"\nየኤሌክትሪክ መጠን መለኪያ");
        hMap.put("voting" ,"\nምርጫ");
        hMap.put("voucher" , "\nደረሰኝ");
        hMap.put("vouchsafe" ,"\nእንደ መብት ፈቀደ");
        hMap.put("vow" ,"\nማለ ተሳለ ቃልኪዳን ገባ");
        hMap.put("vulgarism" ,"\nየብልግና ንግግር");
        hMap.put("vulgarity" , "\nስድነት");
        hMap.put("vulnerable" , "\nሊጎዳ የሚችልበት ደካማ ጎን");
//w
        hMap.put("wadding" ,"\nእቃ ማሸጊያ");
        hMap.put("waist", "\nወገብ");
        hMap.put("walloping" ,"\nበስመ ቅጣት መቀጥቀጥ");
        hMap.put("warbler" ,"\nየሙዚቃ ቅላፄ የተላበሰ ድምፅ ያላት ወፍ");
        hMap.put("warden" ,"\nተቆጣጣሪ");
        hMap.put("warhead" ,"\nየአረር ጫፍ");
        hMap.put("warp" , "\nድር");
        hMap.put("warrior" ,"\nዘማች ጦረኛ");
        hMap.put("waspish" ,"\nግልፍተኛ");
        hMap.put("welder" , "\nበያጅ");
//x
        hMap.put("x-coordinate" , "\nፈርጅ");
        hMap.put("xenon" ,"\nሽታ ወይም ቀለም አልባ የሆነ የጋዝ አይነት");
        hMap.put("xenomenia" , "\nበጭፍን የውጭ ዜጎችን ማፍቀር");
        hMap.put("x-mas" , "\nየገና በዓል");
        hMap.put("xerox" , "\nፎቶ ኮፒ ማንሽ መሳሪያ");
        hMap.put("xray" , "\nራጅ ኤክስሬይ");
        hMap.put("xylem" , "\nዋሽንዳ  ዋንጥራ ቀባይ");
        hMap.put("xylophone" , "\nየሙዚቃ መሳሪያ አግድም የተደረደረ ብረት ያለውና ድምፅ እንዲያወጣ መዶሻ በሚመስል መሳሪያ የሚመታ");
        hMap.put("xylograpy" , "\nበእንጨት ላይ የመቅረፅ ጥበብ");
        hMap.put("xenophobia" , "\nየውጭ አገር ሰዎችን የመጥላት ስሜት");
        hMap.put("xerophytes" , "\nእፅዋተ በረሃ");

//y
        hMap.put("yacht" ,"\nየሽርሽር ጀልባ");
        hMap.put("yachting" ,"\nየጀልባ ውድድር");
        hMap.put("yak" , "\nበእስያ አህጉር የሚገኝ ጎሽ");
        hMap.put("yammer","\nያለማቋረጥ እየተጯጯሁ ማውራት");
        hMap.put("yardstick","\nያርድ ሶስት ጫማ ርዝመት መለኪያ");
        hMap.put("yashmak" ,"\nአይነርግብ");
        hMap.put("yaw" ,"\nመርከብ ወይም አውሮኘላን አቅጣጫ ቀየረ");
        hMap.put("yawning" ,"\nሰፊ ክፍተት");
        hMap.put("yearling" ,"\nአንድ ዓመት የሚቆይ");
        hMap.put("yearning" ,"\nናፍቆት");
//z
        hMap.put("zealot" ,"\nላመነበት ሀይማኖት ወይም ፖለቲካ በጣም የሚቀና ሰው");
        hMap.put("zealous" ,"\nበቀናኢነት የተሞላ ትልቅ ፍላጎት ያለው");
        hMap.put("zombie" , "\nበደመነፍስ የሚንቀሳቀስ");
        hMap.put("zone","\nክልል ግዛት ክበብ");
        hMap.put("zonked" ,"\nበድካም የዛለ");
        hMap.put("zoologist" , "\nሊቀ ስነ እንስሳ");
        hMap.put("zucchini" ,"\nዝኩኒ የዱባ አይነት");
        hMap.put("zygote" ,"\nውህድ ህዋስ ወንም ፍሬ ብረት");
        hMap.put("zymurgy" ,"\nየቢራ ጠመቃ ጥናት");
        hMap.put("zinc","\nዚንክ");

        return hMap;
    }
}
